### ISSUE TITLE
滑动 后崩溃了

### ISSUE THREAD

**Issue by tianshaokai** [SlamDunk007/StockChart#1]
![image](https://user-images.githubusercontent.com/6706496/84575907-6f04fa00-ade3-11ea-9e7d-dd92458e5e6b.png)

2020-06-14 02:02:29.166 1152-1210/? E/statsd: Found dropped events: 1 error -19 last atom tag 83 from uid 10192
2020-06-14 02:02:32.069 28414-28450/com.guannan.stockchart E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.guannan.stockchart, PID: 28414
    java.lang.ArrayIndexOutOfBoundsException: length=73; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.guannan.chartmodule.chart.KMasterChartView.drawFrame(KMasterChartView.java:140)
        at com.guannan.chartmodule.chart.BaseChartView$DoubleBuffering.run(BaseChartView.java:299)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

1 可以加作者一个微信交流一下 异步线程 绘制view吧

**Comment by SlamDunk007** [comment]
可以的，加qq号私聊吧，530491206，目前已经临时解决掉这个bug

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/84592465-788c7180-ae78-11ea-83a1-796eb1abf56a.png)


新的崩溃点
